name: 'Build'

on: 
  push:
    branchs: [development]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Use actions
      uses: actions/setup-node@v3

    - name: Install npm packages
      run: npm install
